name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:
#sdf
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Add Hugging Face remote
        run: |
          git remote add space https://huggingface.co/spaces/spearb0lt/langchain-search-bot-from-github

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://spearb0lt:$HF_TOKEN@huggingface.co/spaces/spearb0lt/langchain-search-bot-from-github main
