- name: Push to Hugging Face Space
  env:
    HF_TOKEN: ${{ secrets.HF_TOKEN }}
  run: |
    git config user.email "actions@github.com"
    git config user.name "GitHub Actions"
    git push --force https://spearb0lt:$HF_TOKEN@huggingface.co/spaces/spearb0lt/langchain-search-bot-from-github main
